
DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS products;

DROP TABLE IF EXISTS product_inventory;

DROP TABLE IF EXISTS carts;

DROP TABLE IF EXISTS cart_items;

DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS order_items;

DROP TABLE IF EXISTS payments;
